"""한국도로공사 OpenAPI 비공식 Python 클라이언트."""

from kraddr.base import Address, PlaceCoordinate

from .catalog import api_catalog, api_catalog_item, get_api_catalog, get_api_catalog_item
from .client import AsyncKrexClient, KrexClient
from .codes import (
    CarType,
    CongestionLevel,
    CoordinateSystem,
    Direction,
    DiscountType,
    IOType,
    KrexCode,
    RoadOperator,
    TCSType,
    TimeUnit,
)
from .debug import DebugRun, jsonable, redact_sensitive, save_fixture
from .exceptions import (
    KrexAuthError,
    KrexBadRequestError,
    KrexConfigError,
    KrexConnectionError,
    KrexError,
    KrexInvalidParameterError,
    KrexMissingParameterError,
    KrexNetworkError,
    KrexNotFoundError,
    KrexParseError,
    KrexQuotaExceededError,
    KrexServerError,
    KrexServiceUnavailableError,
    KrexTimeoutError,
)
from .models import (
    ApiCatalogItem,
    FoodPrice,
    Incident,
    KrexModel,
    Page,
    RawCoordinate,
    RestArea,
    RestAreaFuelPrice,
    RestAreaRouteFacility,
    RestAreaWeather,
    Route,
    TollFee,
    Tollgate,
    TrafficByIc,
    TrafficFlow,
)

__version__ = "0.1.0"
PROVIDER_NAME = "python-krex-api"

__all__ = [
    "PROVIDER_NAME",
    "Address",
    "AsyncKrexClient",
    "ApiCatalogItem",
    "CarType",
    "CongestionLevel",
    "CoordinateSystem",
    "Direction",
    "DiscountType",
    "DebugRun",
    "FoodPrice",
    "IOType",
    "Incident",
    "KrexCode",
    "KrexAuthError",
    "KrexBadRequestError",
    "KrexClient",
    "KrexConfigError",
    "KrexConnectionError",
    "KrexError",
    "KrexInvalidParameterError",
    "KrexMissingParameterError",
    "KrexModel",
    "KrexNetworkError",
    "KrexNotFoundError",
    "KrexParseError",
    "KrexQuotaExceededError",
    "KrexServerError",
    "KrexServiceUnavailableError",
    "KrexTimeoutError",
    "Page",
    "PlaceCoordinate",
    "RawCoordinate",
    "RestArea",
    "RestAreaFuelPrice",
    "RestAreaRouteFacility",
    "RestAreaWeather",
    "RoadOperator",
    "Route",
    "TCSType",
    "TimeUnit",
    "TollFee",
    "Tollgate",
    "TrafficByIc",
    "TrafficFlow",
    "api_catalog",
    "api_catalog_item",
    "get_api_catalog",
    "get_api_catalog_item",
    "jsonable",
    "redact_sensitive",
    "save_fixture",
    "__version__",
]
